-- =============================================================================
-- ESQUEMA FÍSICO SUITE UPE (DIRECCIÓN DE PROTECCIÓN ESPECIAL - DPE)
-- Base de Datos: GESTION_DATOS_DB (Oracle Database XEPDB1)
-- Principio: Auditoría RAW + Hechos Consolidados de Expedientes Únicos
-- =============================================================================

-- 1. TABLA DE CONTROL DE CARGAS
CREATE TABLE DPE_CARGAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_ARCHIVO VARCHAR2(50) DEFAULT 'UPE_CONSOLIDADO',
    NOMBRE_ARCHIVO VARCHAR2(250) NOT NULL,
    PERIODO_CORTE VARCHAR2(50) NOT NULL,
    USUARIO VARCHAR2(100) DEFAULT 'DIRECTORA_DGNNA',
    FECHA_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_ACTUACIONES NUMBER DEFAULT 0,
    TOTAL_EXPEDIENTES NUMBER DEFAULT 0,
    ESTADO VARCHAR2(20) DEFAULT 'COMPLETADO',
    MENSAJE VARCHAR2(500)
);

-- 2. TABLA CONSOLIDADA DE EXPEDIENTES ÚNICOS UPE
CREATE TABLE DPE_UPE_EXPEDIENTES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CARGA_ID NUMBER NOT NULL,
    NUM_EXPEDIENTE VARCHAR2(100) NOT NULL,
    NUM_EXPEDIENTE_HASH VARCHAR2(64),
    SEDE_UPE VARCHAR2(150) NOT NULL,
    ANIO_INGRESO NUMBER(4),
    FECHA_INGRESO DATE,
    
    -- Demografía (Cifrada con Blind Index para NNA)
    TIPO_DOC VARCHAR2(50),
    NRO_DOC_HASH VARCHAR2(64),
    EDAD_INGRESO NUMBER(3),
    GRUPO_ETARIO VARCHAR2(50), -- G1 (0-5 anos), G2 (6-11 anos), G3 (12-17 anos)
    SEXO VARCHAR2(20),
    DEPARTAMENTO_RES VARCHAR2(100),
    PROVINCIA_RES VARCHAR2(100),
    DISTRITO_RES VARCHAR2(100),
    TIENE_DISCAPACIDAD VARCHAR2(10) DEFAULT 'NO',
    ES_GESTANTE VARCHAR2(10) DEFAULT 'NO',
    INSTITUCION_SOLICITANTE VARCHAR2(200),
    
    -- Tipologías de Vulneración (Indicadores Booleanos)
    TIP_VIOLENCIA_SEXUAL NUMBER(1) DEFAULT 0,
    TIP_VIOLENCIA_FISICA NUMBER(1) DEFAULT 0,
    TIP_VIOLENCIA_PSICOLOGICA NUMBER(1) DEFAULT 0,
    TIP_NEGLIGENCIA NUMBER(1) DEFAULT 0,
    TIP_ABANDONO NUMBER(1) DEFAULT 0,
    TIP_TRABAJO_NNA NUMBER(1) DEFAULT 0,
    TIP_VIDA_CALLE NUMBER(1) DEFAULT 0,
    TIP_TRATA NUMBER(1) DEFAULT 0,
    
    -- Flujo Procesal y Estados D.L. 1297
    TIENE_INICIO VARCHAR2(1) DEFAULT 'S',
    FECHA_RES_INICIO DATE,
    TIPO_PROC_INICIO VARCHAR2(50), -- RIESGO / DESPROTECCION / ACOGIMIENTO DE HECHO / OTROS
    
    TIENE_DECLARACION VARCHAR2(1) DEFAULT 'N',
    FECHA_RES_DECLARACION DATE,
    TIPO_PROC_DECLARADO VARCHAR2(50), -- RIESGO / DESPROTECCION
    
    ESCALO_A_DESPROTECCION VARCHAR2(1) DEFAULT 'N', -- 'S' si paso de Riesgo a Desproteccion
    ESTADO_DECLARACION VARCHAR2(50) DEFAULT 'DECLARADO', -- DECLARADO / SIN_DECLARAR_ATASCADO
    
    TIENE_PTI VARCHAR2(1) DEFAULT 'N',
    FECHA_RES_PTI DATE,
    PERMANENCIA_PTI_MESES NUMBER(4) DEFAULT 0,
    RANGO_PTI VARCHAR2(30), -- MENOR_6M / DE_6A12M / MAYOR_12M
    
    MEDIDA_PROTECCION_TIPO VARCHAR2(100), -- ACOGIMIENTO FAMILIAR / ACOGIMIENTO RESIDENCIAL / SIN MP
    MEDIDA_PROTECCION_DETALLE VARCHAR2(200),
    
    ESTADO_PROCEDIMIENTO VARCHAR2(50) DEFAULT 'EN_TRAMITE', -- EN_TRAMITE / CONCLUIDO / NO_ABRIR / DECLINADO
    FECHA_CONCLUSION DATE,
    MOTIVO_CONCLUSION VARCHAR2(200), -- MAYORIA DE EDAD, LOGROS DEL PTI, ARCHIVAMIENTO, etc.
    
    TOTAL_ACTUACIONES_REG NUMBER(3) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_DPE_EXP_CARGA FOREIGN KEY (CARGA_ID) REFERENCES DPE_CARGAS(ID) ON DELETE CASCADE
);

-- Índices de alto rendimiento analítico
CREATE INDEX IX_DPE_EXP_SEDE ON DPE_UPE_EXPEDIENTES(SEDE_UPE);
CREATE INDEX IX_DPE_EXP_ANIO ON DPE_UPE_EXPEDIENTES(ANIO_INGRESO);
CREATE INDEX IX_DPE_EXP_EST_DEC ON DPE_UPE_EXPEDIENTES(ESTADO_DECLARACION);
CREATE INDEX IX_DPE_EXP_PROC_INC ON DPE_UPE_EXPEDIENTES(TIPO_PROC_INICIO);
CREATE INDEX IX_DPE_EXP_PROC_DEC ON DPE_UPE_EXPEDIENTES(TIPO_PROC_DECLARADO);
CREATE INDEX IX_DPE_EXP_ESCALO ON DPE_UPE_EXPEDIENTES(ESCALO_A_DESPROTECCION);
CREATE INDEX IX_DPE_EXP_RANGO_PTI ON DPE_UPE_EXPEDIENTES(RANGO_PTI);
CREATE INDEX IX_DPE_EXP_EST_PROC ON DPE_UPE_EXPEDIENTES(ESTADO_PROCEDIMIENTO);
CREATE INDEX IX_DPE_EXP_MOT_CONC ON DPE_UPE_EXPEDIENTES(MOTIVO_CONCLUSION);
