-- Ejecutar como administrador de la PDB, nunca como SYSTEM del contenedor raíz.
-- Defina los valores según la política de OGTI antes de ejecutar.
WHENEVER SQLERROR EXIT SQL.SQLCODE

DEFINE AM_PASSWORD = '&1'
DEFINE AM_TABLESPACE = '&2'
DEFINE AM_QUOTA_MB = '&3'

CREATE USER AYUDA_MEMORIA_DB IDENTIFIED BY "&&AM_PASSWORD"
  DEFAULT TABLESPACE &&AM_TABLESPACE
  QUOTA &&AM_QUOTA_MB.M ON &&AM_TABLESPACE;

GRANT CREATE SESSION, CREATE TABLE TO AYUDA_MEMORIA_DB;

-- No otorgar DBA, RESOURCE, UNLIMITED TABLESPACE ni privilegios sobre APELACIONES_DB.
